### ISSUE TITLE
Parse Issue

### ISSUE THREAD

**Issue by arjunbazinga** [VldmrB/youtube-watched#1]
(Possibly) Due to a change in the format of the underlying data, the program doesn't detect any watch files.

**Comment by VldmrB** [comment]
This project is essentially abandoned and likely won't see much more upkeep, if any (I'll update the README to reflect that).

However, I just downloaded a fresh Takeout and it's currently being processed without any issues. Well, except that new projects apparently have a daily quota of 10000 for the API being used, which is barely enough for ~800 records.
Follow the instructions on the webpage carefully (the stuff under the **Add data from Google Takeout** header). Failing that...

The problem is that the app doesn't log/handle some of the errors the way it should to the webpage. I've run into an issue with the API complaining about not being enabled despite it being enabled (and re-enabled just for the sake of it). Creating a new project and enabling the API there and creating a key fixed that. You may be experiencing another error.

See if there's any errors appearing in the terminal from which you launched the app.
